config/routes.rb
ChallengeGame::Application.routes.draw do
  resources :seasons

  resources :roster_players

  root :to => 'leagues#index'
  resources :episodes

  resources :rosters
  get '/setroster' => 'rosters#inputroster'
  put '/setroster' => 'rosters#setroster'

  resources :players

  resources :users

  resources :leagues

  resources :sessions

end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :title
  has_many :players
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all
  end
  def show
    @season = Season.find(params[:id])
    @leagues = League.where(:season_id => @season.id).all
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/index.html.erb
<h1> Challenge Seasons </h1>
<h2>
  <% @seasons.each do |s| %>

  <ul>
      <li><%= link_to s.title, season_path(s.id) %></li>
  </ul>
  <% end %>
</h2>

app/views/seasons/show.html.erb
<h1><%= @season.title %>'s Leagues </h1>
  <h2>
    <div>
      <table id="leagues_list">
        <th>League Name</th> 
        <th>Premier Date</th>
        <% @leagues.each do |l| %>
            <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
              <td><%= link_to l.title, league_path(l.id) %> <br></td>
              <td><%= l.premier %></td>
              <td>
                 
                  <%= link_to 'Join League', new_roster_path(:league_id => l.id), :class =>  "btn btn-primary" %> 
                
              </td>
            </tr> 
        <% end%>    
      </table>
    </div>
  </h2>