config/routes.rb
ChallengeGame::Application.routes.draw do
  resources :seasons

  resources :roster_players

  root :to => 'leagues#index'
  resources :episodes

  resources :rosters
  get '/setroster' => 'rosters#inputroster'
  put '/setroster' => 'rosters#setroster'

  resources :players

  resources :users

  resources :leagues

  resources :sessions

end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :title, :season_id, :premier, :rosters_attributes
  has_many :rosters
  accepts_nested_attributes_for :rosters, allow_destroy: true
  has_many :users, :through => :rosters
  belongs_to :season
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
    @league = League.new
  end

  def create
    @league = League.new(params[:league])
    if @league.save
      redirect_to league_path(@league.id)
    else
      render 'new'
    end
  end
  
  def index
    @leagues = League.all.sort
  end
  def show
    if current_user
      @league = League.find(params[:id])
      @season = Season.find(@league.season_id)
      @rosters = Roster.where(:league_id => @league.id).all
    else
      redirect_to new_user_path
    end
  end
  def edit
    @league = League.find(params[:id])
    @season = Season.find(@league.season_id)
    @players = Player.where(:season_id => @season.id).all
    @number_of_roster_players = (@players.size / @league.rosters.size).round
    @rosters = Roster.where(:league_id => @league.id).all
    # need to build roster players
    
    @league.rosters.each do |rost|
      @number_of_roster_players.times {|n| rost.roster_players.build}
    end
  end
  
  def update
    @league = League.find(params[:id])
    @league.rosters.each_with_index do |roster, rindex|
      params[:league][:rosters_attributes][rindex.to_s][:roster_players_attributes].each_with_index do |attribute, aindex|
      
      roster.roster_players.build(:player_id => attribute[1][:id])
      end
    end
    #call a method to populate roster_players names from players
    if @league.save
      RosterPlayer.sync_names(@league)
      redirect_to action: :show, id: @league.id
    else
      edirect_to action: :new, id: @league.id
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for @league do |l| %>
  <div class="field">
    <%= l.label :title %>
    <%= l.text_field :title %>
  </div>
  <div class="field">
    <%= l.label "Season" %>
    <%= l.select(:season_id, Season.all.collect {|s| [s.title, s.id]}) %>
  </div>
  <div>  
    <%= l.fields_for :rosters do |r| %>
      <%= r.object.name %>
      <%= r.hidden_field :name, :value => r.object.name %>
      <%= r.hidden_field :id, :value => r.object.id %>
        
        <%= r.fields_for :roster_players do |rp| %>
        
        <div>
          Add Player: <%= rp.select(:id, @players.collect{|p| [p.name, p.id]}) %>
        </div>
        
        <% end %>
    <% end %>
  </div>





  <div id = 'create-user-button'>
    <%= l.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Edit the league rosters</h1>

<%= render 'form' %>

app/views/leagues/index.html.erb
<h1>Leagues</h1>
 <% if current_user %>
    <button type="button" class="btn btn-primary"> <%= link_to 'Create League', new_league_path %> </button>
    <% else %>
    <% end %>
<div>
  <table id="leagues_list">
    <th>League Name</th>
    <th>Challenge Season</th>
    <th>Premier Date</th>
    <% @leagues.each do |l| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td>
          <%= link_to l.title, league_path(l.id) %> <br>
          </td>
          <td><%= Season.find(l.season_id).title %>
          </td>
          <td><%= l.premier %>
          </td>
          <% if current_user %>
          <td><button type="button" class="btn btn-primary"> <%= link_to 'Join League', new_roster_path(:league_id => l.id) %> </button></td>
          <% else %>
          <% end %>
        </tr>
    <% end%>
    
  </table>


</div>

app/views/leagues/new.html.erb
<h1>Create a new league</h1>

<%= form_for @league do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.select(:season_id, Season.all.collect {|s| [s.title, s.id]}, {:prompt => "Select Season"}) %>
  </div>
  <div id = 'create-user-button'>
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/show.html.erb
<h1>League <%= @league.title %> for Challenge: <%= @season.title %> </h1>
  <% case current_user.role %> 
    <% when "Administrator", "Creator" %>
      <button type="button" class="btn btn-primary"> <%= link_to 'Populate Teams', edit_league_path(@league) %> </button>
      
  <% end %>
<div>
  <table id="rosters_list">
    <th>Roster Name</th>
    <th>Total Points</th>
    <% @rosters.each do |r| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td><%= link_to r.name, roster_path(r.id) %> <br></td>
          <td><%= r.total_points != nil ? r.total_points : 0  %></td>
        </tr>
    <% end%>   
  </table>
</div>