config/routes.rb
ChallengeGame::Application.routes.draw do
  resources :seasons

  resources :roster_players

  root :to => 'leagues#index'
  resources :episodes

  resources :rosters
  get '/setroster' => 'rosters#inputroster'
  put '/setroster' => 'rosters#setroster'

  resources :players

  resources :users

  resources :leagues

  resources :sessions

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name, :total_points, :season_id
  has_many :episodes
  belongs_to :season

  def self.update_total_points(id)
    @player = Player.find(id)
    @player.total_points = 0 if @player.total_points == nil
    @player.episodes.each {|p| @player.total_points += p.total_points}
    @player.save
    RosterPlayer.update_total_points(@player.id, @player.total_points)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end
  def show
    @player = Player.find(params[:id])
    @episodes = @player.episodes
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.erb
<h1>Players</h1>
<div>

  <table id="players_list">
    <th></th>
    <th>Player Name</th>
    <th>Total Points</th>
    <% @players.each do |p| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td>
            <% if current_user.role == "Administrator" %>
            <button type="button" class="btn btn-primary"> 
            <%= link_to '+ Episode', new_episode_path(:id => p.id) %> 
            </button>
            <% else %>
            <% end %>
          </td>
          <td><%= link_to p.name, player_path(p.id) %> <br></td>
          <td><%= p.total_points != nil ? p.total_points : 0  %></td>
         
        </tr>
    <% end%>   
  </table>
</div>

app/views/players/show.html.erb
<h1> <%= @player.name %> </h1>

<table>
  <th>Episode</th>
  <th>Episode Points</th>
  <% @episodes.each do |e| %>
  <tr>
    <td><%= link_to e.title, episode_path(:id => e.id)%> </td>
    <td><%= e.total_points %> </td>
  </tr>
  <% end %>
</table>